name: Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a test script
        run: |
          echo "Running test..."
          # Force the test to fail
          echo "Test failed!"
          exit 1
